# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "56ec7e8c56ef7fbac1395b1db8c39222"
application_url = "https://visual-stocker-custom.fly.dev"
embedded = true
name = "Visual Stocker Custom"
handle = "visual-stocker-custom"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,write_products"

[auth]
redirect_urls = [
  "https://visual-stocker-custom.fly.dev/auth/callback",
  "https://visual-stocker-custom.fly.dev/auth/shopify/callback",
  "https://visual-stocker-custom.fly.dev/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
