# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ccd4ba6230c1930e35d5907d281e0fe0"
application_url = "https://secrets-conditional-outdoors-benchmark.trycloudflare.com"
embedded = true
name = "Visual Stocker NAG"
handle = "visual-stocker-nag"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,write_products"

[auth]
redirect_urls = [
  "https://secrets-conditional-outdoors-benchmark.trycloudflare.com/auth/callback",
  "https://secrets-conditional-outdoors-benchmark.trycloudflare.com/auth/shopify/callback",
  "https://secrets-conditional-outdoors-benchmark.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
